import {test,expect} from './fixtures';
import {readFile} from 'node:fs/promises';

test('existing registration guides privately to a single reset and fresh login',async({page})=>{
 const email='existing-'+Date.now()+'@example.test';
 const original='orchard velvet lantern compass';
 const next='violet harbor lantern meadow';
 const readMail=()=>readFile(process.env.E2E_MAIL_PATH!,'utf8');
 await page.goto('/');
 await page.getByRole('button',{name:'New user? Create account',exact:true}).click();
 await page.getByLabel('Email',{exact:true}).fill(email);
 await page.getByRole('button',{name:'Send verification code',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Check your email'})).toBeVisible();
 await page.getByRole('button',{name:'I received a registration code',exact:true}).click();
 let mail=await readMail();
 const code=mail.match(/\b[0-9]{7}\b/)![0];
 await page.getByLabel('Verification code (7 digits)',{exact:true}).fill(code);
 await page.getByLabel('New password',{exact:true}).fill(original);
 await page.getByLabel('Confirm password',{exact:true}).fill(original);
 await page.getByRole('button',{name:'Verify and create account',exact:true}).click();
 await expect(page.getByRole('heading',{name:'My files',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await page.getByRole('button',{name:'New user? Create account',exact:true}).click();
 await page.getByLabel('Email',{exact:true}).fill(email.toUpperCase());
 const response=page.waitForResponse(r=>r.url().endsWith('/graphql')&&r.request().postData()?.includes('RequestEmailRegistration')===true);
 await page.getByRole('button',{name:'Send verification code',exact:true}).click();
 expect((await (await response).json()).data.requestEmailRegistration).toBe(true);
 await expect(page.getByRole('heading',{name:'Check your email'})).toBeVisible();
 mail=await readMail();
 expect(mail).toContain('An account already uses this email');
 expect(mail.match(/\b[0-9]{7}\b/)).toBeNull();
 await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();
 let resetRequests=0;
 page.on('request',r=>{if(r.url().endsWith('/graphql')&&r.postData()?.includes('RequestPasswordReset'))resetRequests++;});
 await page.getByRole('button',{name:'Reset password',exact:true}).click();
 await expect(page.getByLabel('Reset code (7 digits)',{exact:true})).toBeVisible();
 expect(resetRequests).toBe(1);
 mail=await readMail();
 expect(mail).toContain('Subject: Reset your Full Stack File Vault password');
 await page.getByLabel('Reset code (7 digits)',{exact:true}).fill(mail.match(/\b[0-9]{7}\b/)![0]);
 await page.getByLabel('New password',{exact:true}).fill(next);
 await page.getByLabel('Confirm password',{exact:true}).fill(next);
 await page.getByRole('button',{name:'Reset password',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Password updated'})).toBeVisible();
 await page.getByRole('button',{name:'Back to sign in',exact:true}).click();
 await page.getByLabel('Username or email',{exact:true}).fill(email);
 await page.getByLabel('Password',{exact:true}).fill(original);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.getByText('The username, email or password was not accepted.')).toBeVisible();
 await page.getByLabel('Password',{exact:true}).fill(next);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.locator('.account-name')).toHaveText(email);
 expect(await page.evaluate(()=>Object.keys(localStorage))).toEqual([]);
});
