import { test, expect } from './fixtures';
import AxeBuilder from '@axe-core/playwright';

test('private folder organization preserves search, tags, sharing and root files', async ({ page }) => {
 await page.setViewportSize({ width: 390, height: 844 });
 await page.goto('/');
 await page.getByLabel('Username or email', { exact: true }).fill('e2e.folders');
 await page.getByLabel('Password', { exact: true }).fill(process.env.E2E_PASSWORD!);
 await page.getByRole('button', { name: 'Sign in', exact: true }).click();
 await expect(page.getByRole('heading', { name: 'My files', exact: true })).toBeVisible();
 await page.getByRole('button', { name: 'New folder', exact: true }).click();
 await page.getByLabel('Folder name', { exact: true }).fill('Work');
 await page.getByRole('button', { name: 'Save folder', exact: true }).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('combobox', { name: 'Browse folders', exact: true }).selectOption({ label: '/Work' });
 await page.getByRole('button', { name: 'New folder', exact: true }).click();
 await page.getByLabel('Folder name', { exact: true }).fill('Reports');
 await page.getByRole('button', { name: 'Save folder', exact: true }).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('combobox', { name: 'Browse folders', exact: true }).selectOption('all');
 await page.getByRole('button', { name: 'Upload files', exact: true }).click();
 await page.getByLabel('Upload tags separated by commas', { exact: true }).fill('work');
 await page.getByLabel('Select files to upload').setInputFiles({ name: 'organized.txt', mimeType: 'text/plain', buffer: Buffer.from('organized private file') });
 await page.getByRole('button', { name: 'Upload selected files' }).click();
 await expect(page.getByText('Uploaded 1 file.', { exact: true })).toBeVisible();
 await page.getByRole('button', { name: 'Move organized.txt', exact: true }).click();
 await page.getByRole('combobox', { name: 'Destination folder', exact: true }).selectOption({ label: '/Work/Reports' });
 await page.getByRole('button', { name: 'Move file', exact: true }).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('combobox', { name: 'Browse folders', exact: true }).selectOption('root');
 await expect(page.getByRole('button', { name: 'Details for organized.txt', exact: true })).toHaveCount(0);
 await page.getByRole('combobox', { name: 'Browse folders', exact: true }).selectOption({ label: '/Work/Reports' });
 await page.getByRole('button', { name: 'Delete empty folder', exact: true }).click();
 await expect(page.getByText('Could not delete this folder.', { exact: false })).toBeVisible();
 await page.getByRole('button', { name: 'Rename folder', exact: true }).click();
 await page.getByLabel('Folder name', { exact: true }).fill('Invoices');
 await page.getByRole('button', { name: 'Save folder', exact: true }).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button', { name: 'Details for organized.txt', exact: true }).click();
 await expect(page.getByRole('dialog')).toContainText('/Work/Invoices');
 await expect(page.getByRole('dialog')).toContainText('work');
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
 await page.getByRole('button', { name: 'Move organized.txt', exact: true }).click();
 await page.getByRole('combobox', { name: 'Destination folder', exact: true }).selectOption('');
 await page.getByRole('button', { name: 'Move file', exact: true }).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button', { name: 'Delete empty folder', exact: true }).click();
 await expect(page.getByRole('combobox', { name: 'Browse folders', exact: true }).locator('option:checked')).toHaveText('/Work');
 await page.getByRole('button', { name: 'Delete empty folder', exact: true }).click();
 await expect(page.getByRole('combobox', { name: 'Browse folders', exact: true })).toHaveValue('root');
 await expect(page.getByRole('button', { name: 'Share organized.txt', exact: true })).toBeVisible();
 const accessibility = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze();
 expect(accessibility.violations).toEqual([]);
});
