// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

// Application queries. Operational readiness is exposed separately at /readyz.
type Query struct {
}

// Non-sensitive application information available without authentication.
type ServiceInfo struct {
	// Human-readable application name, not a stable identifier.
	Name string `json:"name"`
}

// Only CSRF material is returned; authentication tokens are HttpOnly cookies.
type SessionBootstrap struct {
	CsrfToken string `json:"csrfToken"`
}
