package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"balkanid.local/vault/api/internal/auth"
	"balkanid.local/vault/api/internal/graph/model"
)

// BeginSession is the resolver for the beginSession field.
func (r *mutationResolver) BeginSession(ctx context.Context) (*model.SessionBootstrap, error) {
	state, err := auth.BootstrapFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return &model.SessionBootstrap{CsrfToken: state.CSRFToken}, nil
}

// ServiceInfo is the resolver for the serviceInfo field.
func (r *queryResolver) ServiceInfo(ctx context.Context) (*model.ServiceInfo, error) {
	return &model.ServiceInfo{Name: "File Vault Application - secure and Production-Grade"}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
